INSERT INTO category (name, created_at) VALUES ('Pet Shop', NOW());
INSERT INTO category (name, created_at) VALUES ('Arts & Crafts', NOW());
INSERT INTO category (name, created_at) VALUES ('Tools & Home Improvement', NOW());
INSERT INTO category (name, created_at) VALUES ('Clothing, Shoes & Accessories', NOW());

INSERT INTO product (name, description, price, img_url, moment) VALUES ('Bird Seed V1', 'Part of a bird''s nutritious meal.', 10.5, 'https://static.wikia.nocookie.net/looneytunes/images/d/d4/Bird_Seed_Box_Ver._1.png/revision/latest?cb=20150114234938', TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z');
INSERT INTO product (name, description, price, img_url, moment) VALUES ('Matches', 'Regular, everyday matches, good for igniting things.', 5.0, 'https://static.wikia.nocookie.net/looneytunes/images/d/d4/Bird_Seed_Box_Ver._1.png/revision/latest?cb=20150114234938', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z');
INSERT INTO product (name, description, price, img_url, moment) VALUES ('Giant Kite Kit', 'Can be used as a regular kite, or can be used to fly and drop weapons.', 50.0, 'https://static.wikia.nocookie.net/looneytunes/images/a/ae/Giant_Kite_Kit.png/revision/latest?cb=20150114231221', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z');
INSERT INTO product (name, description, price, img_url, moment) VALUES ('Bird Seed V2', 'Silly kiddies, seeds are for birds!', 15.7, 'https://static.wikia.nocookie.net/looneytunes/images/9/99/Bird_Seed_V2.png/revision/latest?cb=20150115181127', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z');
INSERT INTO product (name, description, price, img_url, moment) VALUES ('Glue V1', 'A real sticky adhesive.', 17.3, 'https://static.wikia.nocookie.net/looneytunes/images/0/01/Glue_V1.png/revision/latest?cb=20150115233753', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z');
INSERT INTO product (name, description, price, img_url, moment) VALUES ('Grease', '50% Slippery.', 25.4, 'https://static.wikia.nocookie.net/looneytunes/images/9/91/Grease.png/revision/latest?cb=20150115205052', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z');
INSERT INTO product (name, description, price, img_url, moment) VALUES ('Giant Rubber Band V1', 'Used for giant aerial slingshots to shoot things.', 106.2, 'https://static.wikia.nocookie.net/looneytunes/images/e/e5/Giant_Rubber_Band_V1.png/revision/latest?cb=20150115225528', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z');
INSERT INTO product (name, description, price, img_url, moment) VALUES ('Bumble Bees (One Fifth)', 'A real stinger!', 230.0, 'https://static.wikia.nocookie.net/looneytunes/images/a/af/Bumble_Bees.png/revision/latest?cb=20150115203540', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z');
INSERT INTO product (name, description, price, img_url, moment) VALUES ('Giant Rubber Band V2', 'For Tripping Road Runners.', 250.0, 'https://static.wikia.nocookie.net/looneytunes/images/d/db/Giant_Rubber_Band_V2.png/revision/latest?cb=20150116024900', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z');
INSERT INTO product (name, description, price, img_url, moment) VALUES ('Do-It-Yourself Tornado Kit', 'Let you "seed" your own tornadoes.', 130.5, 'https://static.wikia.nocookie.net/looneytunes/images/0/0b/Tornado_Kit.png/revision/latest?cb=20150116024932', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z');
INSERT INTO product (name, description, price, img_url, moment) VALUES ('Tornado Seeds', 'Part of the Tornado Kit.', 360.7, 'https://static.wikia.nocookie.net/looneytunes/images/4/49/Tornado_Seeds.png/revision/latest?cb=20150116025221', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z');
INSERT INTO product (name, description, price, img_url, moment) VALUES ('Bird Seed V3', 'Now comes in can-packed proportions!', 31.6, 'https://static.wikia.nocookie.net/looneytunes/images/5/5f/Bird_Seed_Ver.3.jpg/revision/latest?cb=20150115193842', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z');
INSERT INTO product (name, description, price, img_url, moment) VALUES ('Giant Rubber Band V3', 'Used for human-slingshots.', 400.0, 'https://static.wikia.nocookie.net/looneytunes/images/f/f2/Giant_Rubber_Band_V3.png/revision/latest?cb=20150116050517', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z');
INSERT INTO product (name, description, price, img_url, moment) VALUES ('Balloon', 'Useful for Hot Air Balloonists.', 10.5, 'https://static.wikia.nocookie.net/looneytunes/images/4/48/Balloon.png/revision/latest?cb=20150115194430', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z');
INSERT INTO product (name, description, price, img_url, moment) VALUES ('Christmas Package Machine', 'Puts anything and or ANYONE into small packaged-wrapped presents.', 1250.5, 'https://static.wikia.nocookie.net/looneytunes/images/0/0b/Xmas_Package_Machine.png/revision/latest?cb=20150117031052', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z');
INSERT INTO product (name, description, price, img_url, moment) VALUES ('Axle Grease', 'Guarantees INDEED to be slippery!', 49.8, 'https://static.wikia.nocookie.net/looneytunes/images/d/d1/Axle_Grease.png/revision/latest?cb=20150117034005', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z');
INSERT INTO product (name, description, price, img_url, moment) VALUES ('Lightning Bolts (with Fat Free Rubber Gloves)', 'Be like the Greek god Zeus and shoot lightning bolts from far distances. Fat Free Rubber Gloves included.', 3500.0, 'https://static.wikia.nocookie.net/looneytunes/images/b/b5/Lightning_Bolts.png/revision/latest?cb=20150114165735', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z');
INSERT INTO product (name, description, price, img_url, moment) VALUES ('Super Outfit', 'Doesn''t give one the ability to fly', 137.9, 'https://static.wikia.nocookie.net/looneytunes/images/6/64/Super_Outfit.png/revision/latest?cb=20150115174842', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z');
INSERT INTO product (name, description, price, img_url, moment) VALUES ('Rocket-Powered Roller Skates', 'Let you skate at unlimited speed', 340.0, 'https://static.wikia.nocookie.net/looneytunes/images/7/74/RocketSkates.png/revision/latest?cb=20150112173336', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z');
INSERT INTO product (name, description, price, img_url, moment) VALUES ('Female Road Runner Costume', 'Let you disguise yourself as a female Road Runner, just watch out for other Coyotes', 290.3, 'https://static.wikia.nocookie.net/looneytunes/images/8/83/Female_Road_Runner_Costume.png/revision/latest?cb=20150115233958', TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z');

INSERT INTO product_category (product_id, category_id) VALUES (1, 1);
INSERT INTO product_category (product_id, category_id) VALUES (2, 3);
INSERT INTO product_category (product_id, category_id) VALUES (3, 2);
INSERT INTO product_category (product_id, category_id) VALUES (4, 1);
INSERT INTO product_category (product_id, category_id) VALUES (5, 2);
INSERT INTO product_category (product_id, category_id) VALUES (5, 3);
INSERT INTO product_category (product_id, category_id) VALUES (6, 3);
INSERT INTO product_category (product_id, category_id) VALUES (7, 2);
INSERT INTO product_category (product_id, category_id) VALUES (8, 1);
INSERT INTO product_category (product_id, category_id) VALUES (9, 2);
INSERT INTO product_category (product_id, category_id) VALUES (10, 2);
INSERT INTO product_category (product_id, category_id) VALUES (11, 2);
INSERT INTO product_category (product_id, category_id) VALUES (12, 1);
INSERT INTO product_category (product_id, category_id) VALUES (13, 2);
INSERT INTO product_category (product_id, category_id) VALUES (14, 2);
INSERT INTO product_category (product_id, category_id) VALUES (15, 2);
INSERT INTO product_category (product_id, category_id) VALUES (16, 3);
INSERT INTO product_category (product_id, category_id) VALUES (17, 2);
INSERT INTO product_category (product_id, category_id) VALUES (17, 3);
INSERT INTO product_category (product_id, category_id) VALUES (17, 4);
INSERT INTO product_category (product_id, category_id) VALUES (18, 4);
INSERT INTO product_category (product_id, category_id) VALUES (19, 4);
INSERT INTO product_category (product_id, category_id) VALUES (20, 2);
INSERT INTO product_category (product_id, category_id) VALUES (20, 4);